AcceptanceTests/AcceptanceTests.Driver/Drivers/DesktopDriver.cs
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

Adding the nuget chromedriver

---

AcceptanceTests/AcceptanceTests.Common/Api/Uris/VideoApiUriFactory.cs

VIH-5733
update uri for conferences today
```
[ ] Yes
[x] No
```

VIH-5733 update todays conference uri path

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj

VIH-5733
update uri for conferences today
```
[ ] Yes
[x] No
```

new package version

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
azure-pipelines.yml

Implement gitversion for package nupkg
```
[ ] Yes
[x] No
```

Set Package Version from GitVersion

---

AcceptanceTests/AcceptanceTests.Common/Driver/DriverSetup.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Strategies/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Strategies/Desktop/Mac/FirefoxMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Strategies/Desktop/Windows/ChromeWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Strategies/Desktop/Windows/EdgeChromiumWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Strategies/Desktop/Windows/FirefoxWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Strategies/Drivers.cs

https://tools.hmcts.net/jira/browse/VIH-5586
- Enable option to set proxy on webdrivers for Zap scan
```
[ ] Yes
[x] No
```

Enable option to set Proxy on Chrome,EdgeChromium and Firefox drivers

---

AcceptanceTests/AcceptanceTests.Common/AudioRecordings/AzureStorageManager.cs
AcceptanceTests/AcceptanceTests.Common/AudioRecordings/FileManager.cs

https://tools.hmcts.net/jira/browse/VIH-6385

VIH-6385 cvp_audio_files

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Test/Helpers/VerifyVideoIsPlayingBuilder.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/CommonSharedSteps.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/LoginSharedSteps.cs
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj
AcceptanceTests/AcceptanceTests.Tests/DriverTests/DesktopLocal.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/DesktopSauceLabs.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/MobileLocal.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/MobileSauceLabs.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/TabletLocal.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/TabletSauceLabs.cs

- Changed to use Angular for MS login
```
[ ] Yes
[x] No
```

Changed to use Angular for MS login

---

AcceptanceTests/AcceptanceTests.Common/Model/Hearing/HearingRole.cs
AcceptanceTests/AcceptanceTests.Common/Model/Mappings/CaseRolesHearingsMapping.cs
AcceptanceTests/AcceptanceTests.Common/Model/Participant/ParyRole.cs

https://tools.hmcts.net/jira/browse/VIH-6640
Rename hearing roles
```
[ ] Yes
[ ] No
```

VIH-6640 Rename hearing roles

---

AcceptanceTests/AcceptanceTests.Common/Model/Case/CaseRole.cs

https://tools.hmcts.net/jira/browse/VIH-6738

VIH-6738 Adding case type Home office

---

AcceptanceTests/AcceptanceTests.Common/Model/UserRole/UserRole.cs

VIH-6765
Added joh to user role
```
[ ] Yes
[x] No
```

VIH-6765 Added joh to user role

---

AcceptanceTests/AcceptanceTests.Common/Configuration/ConfigurationManager.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/SafariDriverStrategy.cs

https://tools.hmcts.net/jira/browse/VIH-7058
- removing the target environment from config builder
```
[ ] Yes
[X] No
```

VIH-7058 removing target environment from config builder

---

AcceptanceTests/AcceptanceTests.Common/Configuration/ConfigurationManager.cs

https://tools.hmcts.net/jira/browse/VIH-7058
- removing the sauce labs JSON from the config builder
```
[ ] Yes
[X] No
```

VIH-7058 removing the sauce labs JSON from config builder

---

AcceptanceTests/AcceptanceTests.Common/Configuration/ConfigurationManager.cs

https://tools.hmcts.net/jira/browse/VIH-7058
- Adding secrets for acceptance test execution in the config builder
```
[ ] Yes
[X] No
```

VIH-7058 Adding option to allow test secrets to be added for acceptance tests

---

AcceptanceTests/AcceptanceTests.Common/Configuration/ConfigurationManager.cs

- Combine User Secrets
```
[ ] Yes
[X] No
```

VIH-7058 Combine User Secrets

---

AcceptanceTests/AcceptanceTests.Common/Exceptions/TestSecretsFileMissingException.cs

- Added missing secrets exception
```
[ ] Yes
[X] No
```

VIH-7058 Added missing secrets exception

---

AcceptanceTests/AcceptanceTests.Common/Configuration/ConfigurationManager.cs

https://tools.hmcts.net/jira/browse/VIH-5552
- reading the useraccounts.json to the config manager
```
[ ] Yes
[X] No
```

VIH-5552 Re-adding user accounts

---

AcceptanceTests/AcceptanceTests.Common/Model/Participant/ParyRole.cs

https://tools.hmcts.net/jira/browse/VIH-6956
- added interpreter hearing role.
```
[ ] Yes
[x] No
```

VIH-6956 Add_Interpreter_hearing_role - added interpreter hearing role

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Tablet/iOS/SafariTabletDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/LoginSharedSteps.cs

https://tools.hmcts.net/jira/browse/VIH-7018
- Configured command timeout and login wait for saucelabs ipad(real device)
```
[ ] Yes
[x] No
```

VIH-7018 Added command timeout and wait for ipad

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

- Reduce dependencies to not use .Net Core 5.0
```
[ ] Yes
[X] No
```

VIH-5552 Reduce dependencies

---

AcceptanceTests/AcceptanceTests.Common/Model/Hearing/HearingType.cs

https://tools.hmcts.net/jira/browse/VIH-5552
- added 'Automated Test' to Hearing Types
```
[ ] Yes
[X] No
```

VIH-5552 Adding the Automated Test hearing type

---

AcceptanceTests/AcceptanceTests.Common/Model/Hearing/HearingType.cs

https://tools.hmcts.net/jira/browse/VIH-5552
- reverting a change on Hearing Type
```
[ ] Yes
[X] No
```

VIH-5552 fix to hearing type

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

- Update to chromedriver version
```
[ ] Yes
[X] No
```

VIH-5552 Update Chrome Driver

---

AcceptanceTests/AcceptanceTests.Common/PageObject/Pages/CommonPages.cs

- update to the locator of beta banner
```
[ ] Yes
[X] No
```

VIH-5552 Update beta banner locator

---

AcceptanceTests/AcceptanceTests.Common/Api/Hearings/NotificationApiManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Uris/NotificationApiUriFactory.cs

https://tools.hmcts.net/jira/browse/VIH-7400
- Added notification end points to verify notifications raised
```
[ ] Yes
[x] No
```

VIH-7400 Updated NotificationApi end points

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

- Update to dependencies
```
[ ] Yes
[X] No
```

VIH-5552 Update to dependencies

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Common/Driver/Settings/SauceLabsOptionsBuilder.cs

- Add date to build name
```
[ ] Yes
[X] No
```

VIH-5552 add date to build name

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj

- update to latest NUnit version
```
[ ] Yes
[X] No
```

VIH-5552 NUnit upgrade

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

- downgrade to .Net Test SDK version
```
[ ] Yes
[X] No
```

VIH-5552 Update to test packages

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj

- added some more test packages
```
[ ] Yes
[X] No
```

VIH-5552 Add more test packages

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs

- adding retry on stale elements
- adding an option to get text of element
```
[ ] Yes
[X] No
```

VIH-5552 Adding GetText whist handling stale element references

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs

- Trim text with get text method
```
[ ] Yes
[X] No
```

VIH-5552 Trim text

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj
AcceptanceTests/AcceptanceTests.Tests/DriverTests/DesktopLocal.cs

https://tools.hmcts.net/jira/browse/VIH-7761
Update Chromedriver to latest
Add logging
Correct code.
```
[ ] Yes
[X] No
```

VIH-7761 Update Chromedriver to latest

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/DriverExtensions.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/WaitHelper.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Settings/SauceLabsOptions.cs

https://tools.hmcts.net/jira/browse/VIH-7793
```
[ ] Yes
[ ] No
```

VIH-7793 - Time zone set to UTC and add better waits on page

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/WaitHelper.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Settings/SauceLabsOptions.cs

VIH-7793 add waithelper calls and remove code that was commented,

---

AcceptanceTests/AcceptanceTests.Common/PageObject/Pages/LoginPage.cs

https://tools.hmcts.net/jira/browse/VIH-7888
Added a property for the sign out title value, which can be checked against by the Acceptance tests.
```
[ ] Yes
[x] No
```

VIH-7888 Added property for Sign out title value

---

AcceptanceTests/AcceptanceTests.Common/Api/Clients/ApiClient.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/WaitHelper.cs

VIH-7878 - Update to wait for web element to disappear

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

Create new Uri object for RemoteWebDriver url path
https://tools.hmcts.net/jira/browse/VIH-8021
Create new Uri object for RemoteWebDriver url path
```
[ ] Yes
[ ] No
```

VIH-8021 - Create new Uri object for RemoteWebDriver url path

---

AcceptanceTests/AcceptanceTests.Common/Api/Clients/ApiClient.cs
AcceptanceTests/AcceptanceTests.Common/Api/Healthchecks/HealthcheckManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Hearings/BaseApiManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Hearings/BookingsApiManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Hearings/TestApiManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Hearings/VideoWebApiManager.cs

VIH-7966
Added logging to verify changes made on desktop
```
[ ] Yes
[ ] No
```

VIH-7966 - Added logging

---

AcceptanceTests/AcceptanceTests.Common/Api/Healthchecks/HealthcheckManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Hearings/BaseApiManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Hearings/TestApiManager.cs
AcceptanceTests/AcceptanceTests.Common/PageObject/Pages/LogOutPage.cs
AcceptanceTests/AcceptanceTests.Common/PageObject/Pages/LogoutSuccessPage.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/LoginSharedSteps.cs

VIH-7966 - Fix to support logoff and then login.

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

https://tools.hmcts.net/jira/browse/VIH-8030
update chrome driver to version 92
```
[ ] Yes
[ ] No
```

VIH-8030 Chrome update to version 92

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/DriverSetup.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs

VIH-7966 - Saucelabs smoke test issue debug statements

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

VIH-7966 - more debug

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

VIH-7966 - added testing remote wait

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

VIH 8030 Uri null check and debug statements

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

VIH-8030 - added Mac debug statements

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

VIH-8030 - change Uri.AbsolutePath to Uri.AbsoluteUri

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

https://tools.hmcts.net/jira/browse/VIH-8021
```
[ ] Yes
[ ] No
```

VIH-8021 - reverting Uri.AbsoluteUri to Uri.AbsolutePath

---

AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs

VIH-8260 - remove what might break tests

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj

update to version 96.x.x.x
```
[ ] Yes
[ ] No
```

VIH-8030-update-chrome-driver

---

AcceptanceTests/AcceptanceTests.Common/Api/Hearings/TestApiManager.cs
AcceptanceTests/AcceptanceTests.Common/Api/Helpers/Polling.cs
AcceptanceTests/AcceptanceTests.Common/Api/Zap.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/DriverExtensions.cs
AcceptanceTests/AcceptanceTests.Common/Test/Helpers/VerifyVideoIsPlayingBuilder.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/CommonSharedSteps.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/LoginSharedSteps.cs
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj
AcceptanceTests/AcceptanceTests.Tests/DriverTests/DesktopLocal.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/DesktopSauceLabs.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/MobileLocal.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/MobileSauceLabs.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/TabletLocal.cs
AcceptanceTests/AcceptanceTests.Tests/DriverTests/TabletSauceLabs.cs

Removal of Thread.Sleep(...)s
https://tools.hmcts.net/jira/browse/VIH-8538
All Thread.Sleep(...)s removed
Not sure as this is part of the investigation, in an attempt to come up with a better solution
```
[ ] Yes
[ ] No
```

VIH-8538 Removal of Thread.Sleep(...)s

---

AcceptanceTests/AcceptanceTests.Common/Api/Zap.cs

https://tools.hmcts.net/jira/browse/VIH-8538
Added ReportAndShutDown method back in as it's used in one of the tests in Video-Web
```
[ ] Yes
[ ] No
```

VIH-8538 ReportAndShutDown method added back in

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

Includes Specflow package update
```
[ ] Yes
[ ] No
```

VIH-7990 - Chromedriver Updates

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

VIH-8030 chrome driver update

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj

- VIH-9139 
- updated nuget packages
```
[ ] Yes
[x] No
```

VIH-9139 updated nuget package reference

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj
azure-pipelines.yml

- [x ] commit messages are meaningful and follow good commit message guidelines
```
[ ] Yes
[ x] No
```

Vih 9375 update packages increase timeouts

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-9375
Reverts all changes made from the last 3 merged pull requests, except for the timeouts
```
[ ] Yes
[x] No
```

VIH-9375 Downgrade to .NET Core 3.1 and revert package upgrades

---

AcceptanceTests/AcceptanceTests.Common/AcceptanceTests.Common.csproj
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/ChromeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/EdgeMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/FirefoxMacDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Mac/SafariDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/ChromeWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/EdgeChromiumWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/EdgeDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/FirefoxWindowsDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Desktop/Windows/InternetExplorerDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Services/EdgeChromiumService.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/Tablet/iOS/SafariTabletDriverStrategy.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Drivers/UserBrowser.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/DriverExtensions.cs
AcceptanceTests/AcceptanceTests.Common/Driver/Helpers/WaitHelper.cs
AcceptanceTests/AcceptanceTests.Common/Test/Steps/LoginSharedSteps.cs
AcceptanceTests/AcceptanceTests.Tests/AcceptanceTests.Tests.csproj
AcceptanceTests/AcceptanceTests.Tests/DriverTests/DesktopLocal.cs
azure-pipelines.yml

https://tools.hmcts.net/jira/browse/VIH-9406
https://tools.hmcts.net/jira/browse/VIH-9418
Upgraded target runtime to .NET 6
Upgraded Selenium to version 4
```
[ ] Yes
[X] No
```

VIH-9406 dotnet6 and Selenium4 upgrade
